spring:
  application:
    name: test-jpa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        generate_statistics: true
        jdbc:
          batch_size: 20
#          batch_versioned_data: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost:5432/testjpa?reWriteBatchedInserts=true
    username: v.laptev
    password: 123456
server:
  address: 127.0.0.1
  port: 8080
  error.whitelabel.enabled: false